RSVP Feature
ThomasGGoodwin/PrcussStdio_Tracker pull request #18
Opened 2022-03-01 16:01 UTC by StevenGrimshaw

- quick fixes for rsvp unit tests
- converted sign in naming to rsvp
- rsvp functionality
- **can only create rsvp by clicking on button by event**

2022-03-01 16:16 UTC, ThomasGGoodwin commented on app/views/dashboards/show.html.erb
> +<%= link_to 'Sign Ins', rsvps_path %><br>
Rename this lik to RSVPs.

2022-03-01 16:22 UTC, ThomasGGoodwin commented on config/locales/devise.en.yml
> +      timeout: "Your session expired. Please rsvp again to continue."
Switch these back to "sign_in".

2022-03-01 16:22 UTC, ThomasGGoodwin commented on config/locales/devise.en.yml
> +      updated_but_not_signed_in: "Your account has been updated successfully, but since your password was changed, you need to rsvp again."
^^

2022-03-01 16:22 UTC, ThomasGGoodwin commented on config/locales/devise.en.yml
> +      already_confirmed: "was already confirmed, please try rsvpg in"
^^

2022-03-01 16:26 UTC, ThomasGGoodwin requested changes
See comments in code.

2022-03-01 16:38 UTC, ThomasGGoodwin approved these changes

2022-03-02 01:49 UTC, ThomasGGoodwin approved these changes

2022-03-02 22:31 UTC, LukeY23 approved these changes
it looks good to me

2022-03-02 22:31 UTC, merged