Attendance report
ThomasGGoodwin/PrcussStdio_Tracker pull request #33
Opened 2022-04-03 00:25 UTC by nassef99

2022-04-03 03:34 UTC, LukeY23 approved these changes

2022-04-03 16:34 UTC, ThomasGGoodwin commented on app/views/users/attendance_report.html.erb
> +        <td><%= Rsvp.where(user_id: user.email).count %></td>
Shouldn't the attendance also be checked here?
Rsvp.where(user_id: user.email, attendance: true)

2022-04-03 16:36 UTC, ThomasGGoodwin requested changes
See my comment.

2022-04-04 06:52 UTC, StevenGrimshaw approved these changes
Looks good, may want to move conditional statement into helper function in future.

2022-04-04 13:08 UTC, ThomasGGoodwin approved these changes

2022-04-04 14:35 UTC, merged